[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "14"

[[headers]]
  for = "/*.js"
    [headers.values]
    Content-Type = "application/javascript"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
